services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teleodontologia_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    ports:
      - "9000:9000" # PHP-FPM
    networks:
      - teleodontologia

  nginx:
    image: nginx:alpine
    container_name: teleodontologia_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - teleodontologia

  frontend:
    image: node:20
    container_name: teleodontologia_frontend
    working_dir: /var/www/html
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - .:/var/www
    ports:
      - "5173:5173" # Vite
    networks:
      - teleodontologia

  postgres:
    image: postgres:15
    container_name: teleodontologia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: teleodontologia
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - teleodontologia

volumes:
  pgdata:

networks:
  teleodontologia:
